services:
  # Laravel App Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - laravel_network

  # Frontend Service
  # frontend:
  #   image: node:21
  #   container_name: frontend
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   command: sh -c "npm install && npm run dev"
  #   networks:
  #     - laravel_network

  # PostgreSQL Service
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: care
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

# Volumes
volumes:
  postgres_data:
    driver: local

# Networks
networks:
  laravel_network:
    driver: bridge
